# Generated by Django 3.0.2 on 2020-01-09 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceticket',
            name='status',
            field=models.CharField(default='raised', max_length=10),
        ),
    ]
