# Generated by Django 3.0.2 on 2020-01-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200109_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceticket',
            name='teams',
            field=models.ManyToManyField(to='api.Team'),
        ),
    ]
