# Generated by Django 3.0.2 on 2020-01-09 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_maintenanceticket_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceticket',
            name='technician_completed',
            field=models.ManyToManyField(blank=True, null=True, related_name='tech_completed', to='api.User'),
        ),
        migrations.AlterField(
            model_name='maintenanceticket',
            name='technician_assigned',
            field=models.ManyToManyField(blank=True, related_name='tech_assigned', to='api.User'),
        ),
    ]
