# Generated by Django 3.0.2 on 2020-01-10 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20200109_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenanceticket',
            name='teams_responded',
            field=models.ManyToManyField(related_name='teams_responded', to='api.Team'),
        ),
        migrations.AlterField(
            model_name='maintenanceticket',
            name='teams',
            field=models.ManyToManyField(related_name='teams_required', to='api.Team'),
        ),
    ]
