# Generated by Django 3.0.2 on 2020-01-11 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200110_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='teams',
            field=models.ManyToManyField(related_name='default_teams', to='api.Team'),
        ),
    ]
