# Generated by Django 3.0.2 on 2020-01-11 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200111_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceticket',
            name='technician_assigned',
            field=models.ManyToManyField(blank=True, null=True, related_name='tech_assigned', to='api.User'),
        ),
    ]
