# Generated by Django 3.0.2 on 2020-01-11 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20200111_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceticket',
            name='raised_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.User'),
        ),
    ]
